import { cardanoCliCommand, commandFunction, MatchingProperties } from './command'

export const cardanoCli = (cliPath: string) => ({
	address: cardanoCliCommand('address', {
		build: commandFunction('build'),
		info: commandFunction('info'),
		keyGen: commandFunction('keyGen'),
		keyHash: commandFunction('keyHash'),
	})(cliPath),
	genesis: cardanoCliCommand('genesis', {
		keyGenGenesis: commandFunction('keyGenGenesis'),
		keyGenDelegate: commandFunction('keyGenDelegate'),
		keyGenUtxo: commandFunction('keyGenUtxo'),
		keyHash: commandFunction('keyHash'),
		getVerKey: commandFunction('getVerKey'),
		initialAddr: commandFunction('initialAddr'),
		initialTxin: commandFunction('initialTxin'),
		create: commandFunction('create'),
		createStaked: commandFunction('createStaked'),
		hash: commandFunction('hash'),
	})(cliPath),
	governance: cardanoCliCommand('governance', {
		createMirCertificate: commandFunction('createMirCertificate'),
		createGenesisKeyDelegationCertificate: commandFunction('createGenesisKeyDelegationCertificate'),
		createUpdateProposal: commandFunction('createUpdateProposal'),
	})(cliPath),
	key: cardanoCliCommand('key', {
		verificationKey: commandFunction('verificationKey'),
		nonExtendedKey: commandFunction('nonExtendedKey'),
		convertByronKey: commandFunction('convertByronKey'),
		convertByronGenesisVkey: commandFunction('convertByronGenesisVkey'),
		convertItnKey: commandFunction('convertItnKey'),
		convertItnExtendedKey: commandFunction('convertItnExtendedKey'),
		convertItnBip32Key: commandFunction('convertItnBip32Key'),
		convertCardanoAddressKey: commandFunction('convertCardanoAddressKey'),
	})(cliPath),
	node: cardanoCliCommand('node', {
		keyGen: commandFunction('keyGen'),
		keyGenKes: commandFunction('keyGenKes'),
		keyGenVrf: commandFunction('keyGenVrf'),
		keyHashVrf: commandFunction('keyHashVrf'),
		newCounter: commandFunction('newCounter'),
		issueOpCert: commandFunction('issueOpCert'),
	})(cliPath),
	query: cardanoCliCommand('query', {
		protocolParameters: commandFunction('protocolParameters'),
		tip: commandFunction('tip'),
		stakeDistribution: commandFunction('stakeDistribution'),
		stakeAddressInfo: commandFunction('stakeAddressInfo'),
		utxo: commandFunction('utxo'),
		ledgerState: commandFunction('ledgerState'),
		protocolState: commandFunction('protocolState'),
		stakeSnapshot: commandFunction('stakeSnapshot'),
		poolParams: commandFunction('poolParams'),
	})(cliPath),
	stakeAddress: cardanoCliCommand('stakeAddress', {
		keyGen: commandFunction('keyGen'),
		build: commandFunction('build'),
		keyHash: commandFunction('keyHash'),
		registrationCertificate: commandFunction('registrationCertificate'),
		deregistrationCertificate: commandFunction('deregistrationCertificate'),
		delegationCertificate: commandFunction('delegationCertificate'),
	})(cliPath),
	stakePool: cardanoCliCommand('stakePool', {
		registrationCertificate: commandFunction('registrationCertificate'),
		deregistrationCertificate: commandFunction('deregistrationCertificate'),
		id: commandFunction('id'),
		metadataHash: commandFunction('metadataHash'),
	})(cliPath),
	textView: cardanoCliCommand('textView', {
		decodeCbor: commandFunction('decodeCbor'),
	})(cliPath),
	transaction: cardanoCliCommand('transaction', {
		buildRaw: commandFunction('buildRaw'),
		sign: commandFunction('sign'),
		witness: commandFunction('witness'),
		assemble: commandFunction('assemble'),
		submit: commandFunction('submit'),
		policyid: commandFunction('policyid'),
		calculateMinFee: commandFunction('calculateMinFee'),
		calculateMinValue: commandFunction('calculateMinValue'),
		txid: commandFunction('txid'),
		view: commandFunction('view'),
	})(cliPath),
})

export default cardanoCli
